set(UTILITY png_commons_utility)
set(COMMONS png_commons)
set(BUFFER_VIEW ${COMMONS}_buffer_view)
set(BUFFER ${COMMONS}_buffer)
set(CHUNK ${COMMONS}_chunk)
set(ADLER32 ${UTILITY}_adler32)
set(CRC32 ${UTILITY}_crc32)
set(ENDIAN ${UTILITY}_endian)
set(MEMORY_LITERALS ${UTILITY}_memory_literals)
set(PIXEL_FORMATS ${UTILITY}_pixel_formats)

set(DESERIALIZER png_deserializer)
set(CONSUME_CHUNK ${DESERIALIZER}_consume_chunk)
set(BUF_READER ${CONSUME_CHUNK}_buf_reader)
set(INFLATER ${CONSUME_CHUNK}_inflater)

set(SERIALIZER png_serializer)
set(PRODUCE_CHUNK ${SERIALIZER}_produce_chunk)
set(BUF_WRITER ${PRODUCE_CHUNK}_buf_writer)
set(DEFLATER ${PRODUCE_CHUNK}_deflater)
set(DEFLATER_ATTRIBUTES ${DEFLATER}_attributes)

set(PICTURE png_picture)
set(SECTIONS ${PICTURE}_sections)
set(IHDR ${SECTIONS}_IHDR)
set(PLTE ${SECTIONS}_PLTE)
set(IEND ${SECTIONS}_IEND)

set(BKGD ${SECTIONS}_bKGD)
set(CHRM ${SECTIONS}_cHRM)
set(GAMA ${SECTIONS}_gAMA)
set(HIST ${SECTIONS}_hIST)
set(PHYS ${SECTIONS}_pHYs)
set(TIME ${SECTIONS}_tIME)
set(TRNS ${SECTIONS}_tRNS)

set(PICTURE_DEBUG png_picture_debug)
set(WRITE_SECTION_TO_OSTREAM ${PICTURE_DEBUG}_write_section_to_ostream)
