set(UTILITY pngine_commons_utility)
set(COMMONS pngine_commons)
set(INSTANCE pngine_instance)
set(DEBUG_REPORTEXT pngine_instance_debug_reportEXT)
set(DEVICE pngine_instance_device)
set(QUEUES pngine_instance_device_queues)
set(SURFACEKHR pngine_instance_surfaceKHR)
